-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM BOOK B
    JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES S ON S.BOOK_ID = B.BOOK_ID
WHERE S.SALES_DATE >= '2022-01-01' AND S.SALES_DATE <= '2022-01-31'
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;