-- 코드를 입력하세요
SELECT T.ANIMAL_ID, T.NAME
FROM (
    SELECT I.ANIMAL_ID, I.NAME, DATEDIFF(O.DATETIME, I.DATETIME) AS DIFF
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
) AS T
ORDER BY DIFF DESC LIMIT 2;