SELECT T.CAR_ID, T.CAR_TYPE, T.FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE,
           ROUND(DAILY_FEE * 30 * (100 - CAST(REPLACE(DISCOUNT_RATE, '%', '') AS SIGNED)) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
      ON C.CAR_TYPE = P.CAR_TYPE
     AND P.DURATION_TYPE = '30일 이상'
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
      AND C.CAR_ID NOT IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE START_DATE <= '2022-11-30'
            AND END_DATE >= '2022-11-01'
      )
) AS T
WHERE T.FEE >= 500000
  AND T.FEE < 2000000
ORDER BY T.FEE DESC, T.CAR_TYPE ASC, T.CAR_ID DESC;