-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE),
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / (
        SELECT COUNT(*)
        FROM USER_INFO
        WHERE YEAR(JOINED) = '2021'
    ), 1 ) AS PUCHASED_RATIO
FROM ONLINE_SALE O JOIN USER_INFO I ON O.USER_ID = I.USER_ID
WHERE YEAR(JOINED) = '2021'
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE);