WITH RECURSIVE tmp AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT S.ID, S.PARENT_ID, GENERATION + 1
    FROM tmp JOIN ECOLI_DATA S
    ON tmp.ID = S.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM tmp
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY 2;