-- 코드를 입력하세요
SELECT K.NAME, K.DATETIME
FROM (
    SELECT NAME, DATETIME
    FROM ANIMAL_INS
    WHERE ANIMAL_ID NOT IN (
        SELECT ANIMAL_ID
        FROM ANIMAL_OUTS
    )
    ORDER BY DATETIME DESC
) AS K
ORDER BY K.DATETIME LIMIT 3;