-- 코드를 입력하세요
SELECT HISTORY_ID,
    ROUND(
        (DATEDIFF(END_DATE, START_DATE) + 1) *
        DAILY_FEE * (1 - IFNULL(DISCOUNT_RATE, 0)/100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
AND (
    (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 AND DURATION_TYPE = '90일 이상'
    OR
    (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 AND
    (DATEDIFF(END_DATE, START_DATE) + 1) < 90 AND DURATION_TYPE = '30일 이상'
    OR
    (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 AND
    (DATEDIFF(END_DATE, START_DATE) + 1) < 30 AND DURATION_TYPE = '7일 이상'
)
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;