-- 코드를 입력하세요
SELECT K.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM JULY J
    GROUP BY FLAVOR
    UNION ALL
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR
) AS K
GROUP BY FLAVOR
ORDER BY SUM(TOTAL) DESC LIMIT 3;