-- 코드를 입력하세요
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
    SELECT MEMBER_ID, COUNT(REVIEW_ID) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC LIMIT 1
) AS K
INNER JOIN MEMBER_PROFILE P ON K.MEMBER_ID = P.MEMBER_ID
INNER JOIN REST_REVIEW R ON K.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT
;