SELECT C.ITEM_ID, C.ITEM_NAME, C.RARITY
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS I ON I.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO AS C ON C.ITEM_ID = T.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY C.ITEM_ID DESC;