-- 코드를 작성해주세요
SELECT E2.ID, E2.GENOTYPE, E1.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS E1
JOIN ECOLI_DATA AS E2
ON E1.ID = E2.PARENT_ID
WHERE (E2.GENOTYPE & E1.GENOTYPE) = E1.GENOTYPE
ORDER BY E2.ID;