SELECT MONTH(A.START_DATE) AS MONTH,
       A.CAR_ID,
       COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
      AND START_DATE <  '2022-11-01'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) B ON A.CAR_ID = B.CAR_ID
WHERE A.START_DATE >= '2022-08-01'
  AND A.START_DATE <  '2022-11-01'
GROUP BY MONTH(A.START_DATE), A.CAR_ID
ORDER BY MONTH, A.CAR_ID DESC;