SELECT COUNT(F.ID) AS FISH_COUNT
FROM FISH_INFO AS F
JOIN FISH_NAME_INFO AS N
ON F.FISH_TYPE = N.FISH_TYPE
WHERE F.FISH_TYPE =
    (SELECT FISH_TYPE
     FROM FISH_NAME_INFO
     WHERE FISH_NAME = 'BASS')
OR F.FISH_TYPE =
    (SELECT FISH_TYPE
     FROM FISH_NAME_INFO
     WHERE FISH_NAME = 'SNAPPER');