SELECT T.TOTAL_SCORE AS SCORE, T.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) T
JOIN HR_EMPLOYEES E ON T.EMP_NO = E.EMP_NO
WHERE T.TOTAL_SCORE = (
    SELECT MAX(TOTAL_SCORE)
    FROM (
        SELECT SUM(SCORE) AS TOTAL_SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) X
);