-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', CONCAT(FILE_ID, FILE_NAME, FILE_EXT))
FROM USED_GOODS_FILE F JOIN (
    SELECT BOARD_ID 
    FROM USED_GOODS_BOARD
    GROUP BY BOARD_ID
    ORDER BY VIEWS DESC LIMIT 1
) B ON B.BOARD_ID = F.BOARD_ID
ORDER BY FILE_ID DESC;